
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: eyeaf
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Detects eyes
  description: |
    Detect eyes and face. Find the closest eye too.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    eyeaf:
      plugin: python
      python-version: python3
      source: .
      after: [opencv-snap]
      stage-packages:
        - dlib
        - imutils
        - python-opencv
        - scipy

    opencv-contrib-snap:
      source: https://github.com/opencv/opencv_contrib.git
      source-type: git
      plugin: dump


    opencv-snap:
      source: https://github.com/opencv/opencv.git
      source-type: git
      plugin: cmake
      configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DOPENCV_EXTRA_MODULES_PATH=../../opencv-contrib-snap/src/modules, -DBUILD_opencv_aruco=OFF, -DBUILD_opencv_bgsegm=OFF, -DBUILD_opencv_bioinspired=OFF, -DBUILD_opencv_ccalib=OFF, -DBUILD_opencv_cnn_3dobj=OFF, -DBUILD_opencv_cvv=OFF, -DBUILD_opencv_dnn=OFF, -DBUILD_opencv_dnns_easily_fooled=OFF, -DBUILD_opencv_dpm=OFF, -DBUILD_opencv_fuzzy=OFF, -DBUILD_opencv_hdf=OFF, -DBUILD_opencv_line_descriptor=OFF, -DBUILD_opencv_matlab=OFF, -DBUILD_opencv_optflow=OFF, -DBUILD_opencv_plot=OFF, -DBUILD_opencv_reg=OFF, -DBUILD_opencv_rgbd=OFF, -DBUILD_opencv_saliency=OFF, -DBUILD_opencv_sfm=OFF, -DBUILD_opencv_stereo=OFF, -DBUILD_opencv_structured_light=OFF, -DBUILD_opencv_surface_matching=OFF, -DBUILD_opencv_xfeatures2d=OFF, -DBUILD_opencv_xobjdetect=OFF, -DBUILD_opencv_xphoto=OFF, -DBUILD_opencv_calib3d=OFF, -DBUILD_opencv_cudaarithm=OFF, -DBUILD_opencv_cudabgsegm=OFF, -DBUILD_opencv_cudacodec=OFF, -DBUILD_opencv_cudafilters=OFF, -DBUILD_opencv_cudalegacy=OFF, -DBUILD_opencv_cudaobjdetect=OFF, -DBUILD_opencv_cudaoptflow=OFF, -DBUILD_opencv_cudastereo=OFF, -DBUILD_opencv_cudawarping=OFF, -DBUILD_opencv_cudev=OFF, -DBUILD_opencv_java=OFF, -DBUILD_opencv_shape=OFF, -DBUILD_opencv_stitching=OFF, -DBUILD_opencv_superres=OFF, -DBUILD_opencv_ts=OFF, -DBUILD_opencv_videoio=OFF, -DBUILD_opencv_videostab=OFF, -DBUILD_opencv_viz=OFF]
      after: [opencv-contrib-snap]
      build-packages:
        - build-essential
        - extra-cmake-modules
        - pkg-config
        - libavformat-dev
        - libavdevice-dev
        - libswscale-dev
        - libgavl-dev
        - libcairo2-dev
        - libpython2.7
        - libpython-stdlib
        - libpython3.5
        - libpython3-stdlib
        - python-numpy
        - python3-numpy

  apps:
    eyeaf:
      command: python detect_face_parts.py
      environment:
        XWAYLAND_FULLSCREEN_WINDOW_HINT: title="opencv-demo"
      slots: [ x11 ]
      plugs:
        - camera
        - home
        - opengl
        - wayland
        - x11-plug


